# Project information
site_name: 'Template Docs'
site_description: 'Template'
site_author: 'me'
#site_url: 'site'

# Repository
#repo_name: ''
#repo_url: 'https://github.com/curollo/mkdocs-starter-pack'

# Copyright
copyright: 'Copyright &copy; 2024 <a href="https://github.com/curollo" target=_blank>arula</a>'

# Plugins
plugins:
  - search
    #- alternate-link
    #- offline

# Extensions
markdown_extensions:
  - md_in_html
  #  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
    #permalink: "¤"
      permalink: true
  - pymdownx.blocks.admonition:
     types:
      - new
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - danger
      - bug
      - example
      - quote

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo: 'resources/logo.png'
    #favicon: 'resources/logo.png'
  font: false
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: red
      primary: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Customisation
extra:
  generator: true
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/login

extra_javascript:
  - 'resources/katex.js'
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - 'resources/custom.css'
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
- Home: index.md
- Getting Started:
    - Quickstart: quickstart.md
- About:
    - Changelog: about/changelog.md
      #    - Contributing to Docs: about/style-guide.md
